<?php

declare(strict_types=1);

$dumpPath = $argv[1] ?? '/DataBaseDump.sql';
if (!is_file($dumpPath)) {
    $fallbackPath = dirname(__DIR__) . '/DataBaseDump.sql';
    $dumpPath = is_file($fallbackPath) ? $fallbackPath : $dumpPath;
}

if (!is_file($dumpPath)) {
    fwrite(STDERR, "SQL dump not found at {$dumpPath}\n");
    exit(1);
}

$host = getenv('POSTGRES_HOST') ?: 'postgres';
$port = getenv('POSTGRES_PORT') ?: '5432';
$database = getenv('POSTGRES_DB') ?: 'bookswap_vectors';
$username = getenv('POSTGRES_USER') ?: 'developer';
$password = getenv('POSTGRES_PASSWORD') ?: 'secret123';

$dsn = "pgsql:host={$host};port={$port};dbname={$database}";
$pdo = new PDO($dsn, $username, $password, [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
]);

$dumpSql = file_get_contents($dumpPath);
if ($dumpSql === false) {
    fwrite(STDERR, "Failed to read SQL dump at {$dumpPath}\n");
    exit(1);
}

$pdo->beginTransaction();

try {
    createSchema($pdo);

    $insertBlocks = parseInsertBlocks($dumpSql);
    $importOrder = ['users', 'books', 'book_swap_requests', 'direct_messages'];

    foreach ($importOrder as $table) {
        if (!isset($insertBlocks[$table])) {
            echo "No rows found for {$table}\n";
            continue;
        }

        $imported = 0;
        foreach ($insertBlocks[$table] as $block) {
            $imported += insertRows($pdo, $table, $block['columns'], $block['rows']);
        }

        echo "Imported {$imported} rows into {$table}\n";
    }

    addIndexesAndConstraints($pdo);
    resetSequences($pdo);

    $pdo->commit();
    echo "Migration completed successfully.\n";
} catch (Throwable $e) {
    $pdo->rollBack();
    fwrite(STDERR, "Migration failed: {$e->getMessage()}\n");
    exit(1);
}

function createSchema(PDO $pdo): void
{
    $pdo->exec(<<<'SQL'
DROP TABLE IF EXISTS direct_messages CASCADE;
DROP TABLE IF EXISTS book_swap_requests CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    fname varchar(20) NOT NULL,
    lname varchar(20) NOT NULL,
    role varchar(10) NOT NULL DEFAULT 'GUEST',
    email varchar(60) NOT NULL,
    password_hash text NOT NULL,
    address varchar(30),
    post_code varchar(10),
    country varchar(25),
    joined_at timestamp DEFAULT CURRENT_TIMESTAMP,
    resset_token text,
    resset_token_expiry timestamp,
    "isActive" smallint,
    "isVerified" smallint,
    swap_tokens integer NOT NULL DEFAULT 0,
    state varchar(20) NOT NULL,
    phone_number varchar(20),
    bio text,
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'USER', 'GUEST'))
);

CREATE TABLE books (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    shared_by integer,
    title varchar(255) NOT NULL,
    author varchar(255) NOT NULL,
    isbn varchar(20) NOT NULL,
    published_year smallint NOT NULL,
    genre varchar(100),
    description text,
    cover_image_url varchar(255),
    thumbnail_image_url varchar(255),
    book_condition varchar(10) NOT NULL DEFAULT 'Unknown',
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
    page_count integer,
    is_active smallint NOT NULL DEFAULT 1,
    owner_review text,
    embedding vector(1024),
    CONSTRAINT books_condition_check CHECK (book_condition IN ('Unknown', 'New', 'Good', 'Fair', 'Poor'))
);

CREATE TABLE book_swap_requests (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    book_id integer NOT NULL,
    owner_id integer NOT NULL,
    requester_id integer,
    owner_action_token text,
    requester_action_token text,
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    shipping_street varchar(100),
    shipping_post_code varchar(15),
    shipping_state varchar(50),
    shipping_country varchar(50),
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    closed_at timestamp,
    shipping_cost double precision,
    CONSTRAINT book_swap_requests_status_check CHECK (status IN ('PENDING', 'SHIPPINGPAID', 'SHIPPED', 'DELIVERED', 'COMPLETED', 'TAKENDOWN'))
);

CREATE TABLE direct_messages (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    sender_id integer NOT NULL,
    recipient_id integer NOT NULL,
    message text NOT NULL,
    is_read smallint DEFAULT 0,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);
SQL);
}

/**
 * @return array<string, array<int, array{columns: array<int, string>, rows: array<int, array<int, mixed>>}>>
 */
function parseInsertBlocks(string $sql): array
{
    preg_match_all('/INSERT INTO `([^`]+)` \((.*?)\) VALUES\s*/s', $sql, $matches, PREG_SET_ORDER | PREG_OFFSET_CAPTURE);

    $blocks = [];
    foreach ($matches as $match) {
        $table = $match[1][0];
        $valuesStart = $match[0][1] + strlen($match[0][0]);
        $valuesEnd = findStatementEnd($sql, $valuesStart);
        $columns = array_map(
            static fn (string $column): string => trim($column, " `\t\n\r\0\x0B"),
            explode(',', $match[2][0])
        );

        $blocks[$table][] = [
            'columns' => $columns,
            'rows' => parseValues(substr($sql, $valuesStart, $valuesEnd - $valuesStart)),
        ];
    }

    return $blocks;
}

function findStatementEnd(string $sql, int $start): int
{
    $length = strlen($sql);
    $inString = false;

    for ($i = $start; $i < $length; $i++) {
        $char = $sql[$i];

        if ($inString) {
            if ($char === '\\') {
                $i++;
                continue;
            }

            if ($char === "'") {
                $inString = false;
            }

            continue;
        }

        if ($char === "'") {
            $inString = true;
            continue;
        }

        if ($char === ';') {
            return $i;
        }
    }

    throw new RuntimeException('Could not find INSERT statement terminator');
}

/**
 * @return array<int, array<int, mixed>>
 */
function parseValues(string $valuesSql): array
{
    $rows = [];
    $length = strlen($valuesSql);
    $i = 0;

    while ($i < $length) {
        skipWhitespaceAndCommas($valuesSql, $i, $length);
        if ($i >= $length) {
            break;
        }

        if ($valuesSql[$i] !== '(') {
            throw new RuntimeException("Expected row start at offset {$i}");
        }
        $i++;

        $row = [];
        while ($i < $length) {
            skipWhitespace($valuesSql, $i, $length);
            $row[] = parseValue($valuesSql, $i, $length);
            skipWhitespace($valuesSql, $i, $length);

            if ($i >= $length) {
                throw new RuntimeException('Unexpected end of VALUES block');
            }

            if ($valuesSql[$i] === ',') {
                $i++;
                continue;
            }

            if ($valuesSql[$i] === ')') {
                $i++;
                $rows[] = $row;
                break;
            }

            throw new RuntimeException("Expected comma or row end at offset {$i}");
        }
    }

    return $rows;
}

function parseValue(string $sql, int &$i, int $length): mixed
{
    if ($sql[$i] === "'") {
        return parseQuotedString($sql, $i, $length);
    }

    $start = $i;
    while ($i < $length && $sql[$i] !== ',' && $sql[$i] !== ')') {
        $i++;
    }

    $token = trim(substr($sql, $start, $i - $start));
    if (strcasecmp($token, 'NULL') === 0) {
        return null;
    }

    return $token;
}

function parseQuotedString(string $sql, int &$i, int $length): string
{
    $i++;
    $value = '';

    while ($i < $length) {
        $char = $sql[$i];

        if ($char === "'") {
            $i++;
            return $value;
        }

        if ($char === '\\') {
            $i++;
            if ($i >= $length) {
                $value .= '\\';
                break;
            }

            $escaped = $sql[$i];
            $value .= match ($escaped) {
                '0' => "\0",
                'n' => "\n",
                'r' => "\r",
                't' => "\t",
                'b' => "\b",
                'Z' => chr(26),
                default => $escaped,
            };
            $i++;
            continue;
        }

        $value .= $char;
        $i++;
    }

    throw new RuntimeException('Unterminated quoted string in dump');
}

function skipWhitespaceAndCommas(string $sql, int &$i, int $length): void
{
    while ($i < $length && (ctype_space($sql[$i]) || $sql[$i] === ',')) {
        $i++;
    }
}

function skipWhitespace(string $sql, int &$i, int $length): void
{
    while ($i < $length && ctype_space($sql[$i])) {
        $i++;
    }
}

/**
 * @param array<int, string> $columns
 * @param array<int, array<int, mixed>> $rows
 */
function insertRows(PDO $pdo, string $table, array $columns, array $rows): int
{
    if ($rows === []) {
        return 0;
    }

    $quotedColumns = array_map(static fn (string $column): string => quoteIdentifier($column), $columns);
    $placeholders = array_map(static fn (string $column): string => ':' . $column, $columns);
    $sql = sprintf(
        'INSERT INTO %s (%s) VALUES (%s)',
        quoteIdentifier($table),
        implode(', ', $quotedColumns),
        implode(', ', $placeholders)
    );
    $stmt = $pdo->prepare($sql);

    $count = 0;
    foreach ($rows as $row) {
        if (count($row) !== count($columns)) {
            throw new RuntimeException("Column/value count mismatch for {$table}");
        }

        foreach ($columns as $index => $column) {
            $value = normalizeValue($column, $row[$index]);
            $stmt->bindValue(':' . $column, $value, $value === null ? PDO::PARAM_NULL : PDO::PARAM_STR);
        }

        $stmt->execute();
        $count++;
    }

    return $count;
}

function normalizeValue(string $column, mixed $value): mixed
{
    if ($value === null) {
        return null;
    }

    if (in_array($column, ['id', 'shared_by', 'book_id', 'owner_id', 'requester_id', 'published_year', 'page_count', 'is_active', 'is_read', 'isActive', 'isVerified', 'swap_tokens'], true)) {
        return (string) (int) $value;
    }

    if ($column === 'shipping_cost') {
        return (string) (float) $value;
    }

    return $value;
}

function quoteIdentifier(string $identifier): string
{
    return '"' . str_replace('"', '""', $identifier) . '"';
}

function addIndexesAndConstraints(PDO $pdo): void
{
    $pdo->exec(<<<'SQL'
ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE books ADD CONSTRAINT books_pkey PRIMARY KEY (id);
ALTER TABLE book_swap_requests ADD CONSTRAINT book_swap_requests_pkey PRIMARY KEY (id);
ALTER TABLE direct_messages ADD CONSTRAINT direct_messages_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX users_email_idx ON users (email);
CREATE INDEX books_shared_by_idx ON books (shared_by);
CREATE INDEX book_swap_requests_book_id_idx ON book_swap_requests (book_id);
CREATE INDEX book_swap_requests_owner_id_idx ON book_swap_requests (owner_id);
CREATE INDEX book_swap_requests_requester_id_idx ON book_swap_requests (requester_id);
CREATE INDEX book_swap_requests_status_idx ON book_swap_requests (status);
CREATE UNIQUE INDEX book_swap_requests_owner_action_token_idx ON book_swap_requests (owner_action_token) WHERE owner_action_token IS NOT NULL;
CREATE UNIQUE INDEX book_swap_requests_requester_action_token_idx ON book_swap_requests (requester_action_token) WHERE requester_action_token IS NOT NULL;
CREATE INDEX direct_messages_recipient_id_idx ON direct_messages (recipient_id);
CREATE INDEX direct_messages_conversation_idx ON direct_messages (sender_id, recipient_id);

ALTER TABLE books
    ADD CONSTRAINT books_shared_by_fk FOREIGN KEY (shared_by) REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE book_swap_requests
    ADD CONSTRAINT book_swap_requests_book_fk FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT book_swap_requests_owner_fk FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    ADD CONSTRAINT book_swap_requests_requester_fk FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE direct_messages
    ADD CONSTRAINT direct_messages_sender_fk FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE,
    ADD CONSTRAINT direct_messages_recipient_fk FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE;
SQL);
}

function resetSequences(PDO $pdo): void
{
    foreach (['users', 'books', 'book_swap_requests', 'direct_messages'] as $table) {
        $quotedTable = quoteIdentifier($table);
        $pdo->exec("SELECT setval(pg_get_serial_sequence('{$table}', 'id'), COALESCE((SELECT MAX(id) FROM {$quotedTable}), 1), true)");
    }
}
